
export const USER_REQUEST = 'USER_REQUEST';
export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_FAILURE = 'USER_FAILURE';

export const GROUP_REQUEST = 'GROUP_REQUEST';
export const GROUP_SUCCESS = 'GROUP_SUCCESS';
export const GROUP_FAILURE = 'GROUP_FAILURE';

export const LIST_REQUEST = 'LIST_REQUEST';
export const LIST_SUCCESS = 'LIST_SUCCESS';
export const LIST_FAILURE = 'LIST_FAILURE';
export const LIST_SAVE_REQUEST = 'LIST_SAVE_REQUEST';
export const LIST_SAVE_SUCCESS = 'LIST_SAVE_SUCCESS';
export const LIST_SAVE_FAILURE = 'LIST_SAVE_FAILURE';
